### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by MBskier** [taurgis/homebridge-iRobot-v2#13]
### Describe Your Problem:

My logs keep having the roomba disconnect. I saw the note that this may be due to other integrations. I previously used a Homebridge plugin, IFTTT, and yonomi, but they all are disconnected and the devices have been reset since. 

### Logs:

```shell
[13/10/2024, 07:37:30] [iRobot] Roomba Roomba  connection closed.
[13/10/2024, 07:37:31] [iRobot] Successfully reconnected to roomba Roomba
[13/10/2024, 07:37:31] [iRobot] Roomba Roomba  connection closed.
[13/10/2024, 07:37:32] [iRobot] Successfully reconnected to roomba Roomba
[13/10/2024, 07:37:33] [iRobot] Roomba Roomba  connection closed.
[13/10/2024, 07:37:34] [iRobot] Successfully reconnected to roomba Roomba
[13/10/2024, 07:37:34] [iRobot] Roomba Roomba  connection closed.
[13/10/2024, 07:37:35] [iRobot] Successfully reconnected to roomba Roomba
[13/10/2024, 07:37:35] [iRobot] Roomba Roomba  connection closed.
```

### Config:

```shell
{
    "name": "iRobot",
    "email": "*",
    "password": "*",
    "roombas": [
        {
            "autoConfig": true,
            "info": {
                "ver": 2
            }
        }
    ],
    "manualDiscovery": false,
    "lowBattery": 20,
    "offAction": "pause:dock",
    "status": "cycle:clean",
    "eveStatus": "inverted:cycle:clean",
    "bin": "filter:contact",
    "ignoreMultiRoomBin": false,
    "hideStuckSensor": false,
    "disableMultiRoom": false,
    "_bridge": {
        "username": "0E:48:11:AE:B3:BE",
        "port": 52012
    },
    "platform": "iRobotPlatform"
}
```

### Node Version:

v20.18.0

### NPM Version:

Sorry I can’t find this info

### Homebridge Version:

v1.8.4

### Plugin Version:

v3.2.1

### Operating System:

Raspberian

**Comment by taurgis** [comment]
Have you tried restarting the Roomba itself? This sometimes also solves the error.

**Comment by bervoiv** [comment]
I have the same problem.
Restart of roomba did not solve the problem.
I also disabled all other child plugins just to be sure.
I’m moving from google home into Apple HomeKit.
Also removed the roomba from my google home integration and even logged out from the iRobot app itself.
All the above did not solve the issue.
Running HomeBridge from my NAS and the iRobot is a Roomba 960

*Edit*
Problem persists in versions below:
v3.2.0-alpha.8
v3.2.3-alpha.1
v3.2.3-alpha.0

Re-install of the plugin didn’t solve it either.

**Comment by taurgis** [comment]
As someone else also reported the Roomba 960 as not working, I'm afraid it is not supported.
