### ISSUE TITLE
Supported Device: 

### ISSUE THREAD

**Issue by jojoballa** [taurgis/homebridge-iRobot-v2#16]
### Roomba Model:

Romba 698

### Did It Work

No

**Comment by jojoballa** [comment]
Hello,

Since latest updates the Romba 698 doe not reconnect any more
shows  Error

I have only the original Romba App on my iPhone, and disconnected the unit form the App
but still having the Problem See att. Info.

Ip Adress ist still the same and checked, Restarted Bridge a view times, still not working


Thank You in advance

10/18/2024, 3:17:55 PM] [iRobot] Successfully reconnected to roomba Leo
[10/18/2024, 3:17:55 PM] [iRobot] Roomba Leo  has been reconnecting too many times in the last 30 seconds, stopping... 
 This is probably related due to the limited (1) connection slots on the Roomba, try closing any other application on services that might be connected to the Roomba. 
 If this error persists, try restarting the Homebridge service or the Roomba, it is possible the IP address of the Roomba has changed.
[10/18/2024, 3:17:55 PM] [iRobot] Roomba Leo  has been stopped, trying to reconnect in 5 minutes...
[10/18/2024, 3:17:55 PM] [iRobot] Roomba Leo  connection clos

**Comment by taurgis** [comment]
I'm afraid the 9xx series is not compatible, as multiple people have reported it is not working. I will update the Readme.

**Comment by jojoballa** [comment]
Thank you for the Info, please make sure it is not a 9xx Series it is a  Romba 698 
regrads

**Comment by taurgis** [comment]
Sorry, I meant the 6xx series, this is the third in that range that does not appear to be working. 

Since I only own an i7 and Braava M6, I can't test the other ranges unless people start donating 500$ + devices to me, which I don't see happening soon.  😅

Once one of those dies and I need a new one (and iRobot is the replacement), I can look at others.
