### ISSUE TITLE
Support Request: What the motion sensor is for?

### ISSUE THREAD

**Issue by redeemer666** [taurgis/homebridge-iRobot-v2#25]
### Describe Your Problem:

Hello there, I'm a new user and I don't understand the motion sensors for my two robots (Roomba and Braava). I disabled the "bin detection" on the plugin, but still have these two motion sensors that shows up (one per robot).

What's that for? 

Thanks a lot for your help

### Expected behavior:

--

### Logs:

```shell
No logs to show
```

### Config:

```shell
--
```

### Node Version:

22

### NPM Version:

--

### Homebridge Version:

latest

### Plugin Version:

latest stable

### Operating System:

Raspberian

**Comment by remlio** [comment]
In addition to the bin sensor, there's also the stuck sensor for a situation when your robot’s need your help.

**Comment by taurgis** [comment]
The second one is indeed the stuck sensor. Is this info sufficient?
