### ISSUE TITLE
Support Request: Unable to find Roomba Devices with Blid

### ISSUE THREAD

**Issue by dukeseb** [taurgis/homebridge-iRobot-v2#9]
### Describe Your Problem:

The plugin shows its not able to connect with the provided BLID

### Logs:

```shell
Failed to connect roomba: Kevin with error: No Roomba Found
With Blid: **************************
```

### Config:

```shell
"name": "iRobot",
            "email": "*************",
            "password": "**************",
            "roombas": [
                {
                    "autoConfig": true,
                    "info": {
                        "ver": 2
                    }
                }
            ],
            "manualDiscovery": false,
            "lowBattery": 20,
            "offAction": "pause:dock",
            "status": "cycle:clean",
            "eveStatus": "inverted:cycle:clean",
            "bin": "filter:contact",
            "ignoreMultiRoomBin": true,
            "hideStuckSensor": false,
            "disableMultiRoom": false,
            "platform": "iRobotPlatform"
```

### Node Version:

20.17.0

### NPM Version:

10.8.2

### Homebridge Version:

1.8.3

### Plugin Version:

3.2.1

### Operating System:

Debian

**Comment by taurgis** [comment]
Is the Roomba on the same local network as your Homebridge?

**Comment by dukeseb** [comment]
> Is the Roomba on the same local network as your Homebridge?

No its on my Iot Network

**Comment by taurgis** [comment]
The plugin uses MQTT across the local network, so it will not work if it is on a separate one.

**Comment by dukeseb** [comment]
> The plugin uses MQTT across the local network, so it will not work if it is on a separate one.

Would it work if I manually configured my devices and allowed homebridge to communicate back and forth between its network and my IoT network?

**Comment by taurgis** [comment]
Yes, the manual configuration should allow you to do this. You can get the required parameters from the "autoconfig" (blid and such)
